// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpTLixJLFyZgL0VPoxsSRJ7fIdzQDfoAQ',
    appId: '1:548906212262:web:ce1d894e95d6cc6b0b8d67',
    messagingSenderId: '548906212262',
    projectId: 'test-store2',
    authDomain: 'test-store2.firebaseapp.com',
    storageBucket: 'test-store2.appspot.com',
    measurementId: 'G-6DFEH6WL7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwVzI9a1lN-N4uVFdnJwh4Lz-_lpCefJg',
    appId: '1:548906212262:android:e9155253ccbe66bb0b8d67',
    messagingSenderId: '548906212262',
    projectId: 'test-store2',
    storageBucket: 'test-store2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6GuuVl2j50fupHl_o2ROxfJpBdwV6DI4',
    appId: '1:548906212262:ios:5d6ae2c9fceab4860b8d67',
    messagingSenderId: '548906212262',
    projectId: 'test-store2',
    storageBucket: 'test-store2.appspot.com',
    iosBundleId: 'com.example.gstoreOfficial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6GuuVl2j50fupHl_o2ROxfJpBdwV6DI4',
    appId: '1:548906212262:ios:5d6ae2c9fceab4860b8d67',
    messagingSenderId: '548906212262',
    projectId: 'test-store2',
    storageBucket: 'test-store2.appspot.com',
    iosBundleId: 'com.example.gstoreOfficial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpTLixJLFyZgL0VPoxsSRJ7fIdzQDfoAQ',
    appId: '1:548906212262:web:7959c940f305ce800b8d67',
    messagingSenderId: '548906212262',
    projectId: 'test-store2',
    authDomain: 'test-store2.firebaseapp.com',
    storageBucket: 'test-store2.appspot.com',
    measurementId: 'G-1QK5XP2Z8S',
  );
}
